command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "<YOUR_WAREHOUSE_ID>"
  - name: DATABRICKS_CATALOG
    value: "<YOUR_CATALOG>"
  - name: DATABRICKS_SCHEMA
    value: "chd_demo"
  - name: DATABRICKS_MAS_ENDPOINT
    value: "<YOUR_MAS_ENDPOINT>"
  - name: DATABRICKS_MMM_ENDPOINT
    value: "<YOUR_MMM_ENDPOINT>"
